import { StyleSheet } from "react-native";
import theme from "../../styles/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.colors.primary_bg, },
  header1: {
    backgroundColor: theme.colors.primary_bg,
    flexDirection: "row",
    paddingTop: 20,
    paddingBottom: 5,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  header2: {
    backgroundColor: theme.colors.primary_bg,
    flexDirection: "row",
    paddingBottom: 0,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  header3: {
    backgroundColor: theme.colors.primary_bg,
    flexDirection: "row",
    paddingBottom: 10,
    paddingHorizontal: 10,
    alignItems: "center",
  },
  headerLine: {
    fontSize: 20,
    fontFamily: "FuturaPT-Bold",
    color: theme.colors.gold_deep,
    marginBottom: 5,
    marginRight: 10,
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.black,
    marginBottom: 5,
    marginRight: 20,
  },
  headerArrow: {
    fontSize: 24,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.black,
    marginBottom: 5,
    marginRight: 20,
  },
  headerdesc: {
    fontSize: 15,
    fontFamily: "FuturaPT-Light",
    color: theme.colors.black,
    marginBottom: 5,
    marginRight: 10,
  },
  headerdescbold: {
    fontSize: 16,
    fontFamily: "FuturaPT-Bold",
    color: theme.colors.gold_deep,
    marginBottom: 5,
    marginRight: 10,
  },
  content: { flex: 1, flexDirection: "row" },
  sidebar: {
    width: 100,
    backgroundColor: theme.colors.primary_bg,
    borderRightWidth: 1,
    borderRightColor: theme.colors.gray_text,
  },
  categoryItem: {
    width: 100,
    height: 121,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 15,
  },
  activeCategoryItem: { backgroundColor: theme.colors.gold_deep },
  categoryText: {
    fontSize: 15,
    textAlign: "center",
    color: theme.colors.black,
    fontWeight: "500",
  },
  activeCategoryText: { color: theme.colors.white, fontWeight: "600" },
  menuContainer: {
    flex: 1,
    backgroundColor: theme.colors.primary_bg,
    paddingTop: 15,
  },
  categoryTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  menuList: { paddingBottom: 20 },
  menuItem: {
    borderRadius: 12,
    padding: 15,
    marginBottom: 10,
  },
  selectedMenuItem: {
    borderColor: "#8B4513",
    borderWidth: 2,
    backgroundColor: "#fff8f0",
  },
  menuItemHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  menuItemPic: {
    width: 94,
    height: 94,
    marginRight: 12,
    marginTop: 2,
    borderRadius: 8,
  },
  menuItemInfo: {
    flex: 1,
    height: 100,
  },
  menuItemName: {
    fontFamily: "FuturaPT-Demi",
    fontSize: 16,
    color: theme.colors.black,
    marginBottom: 4,
  },
  menuItemDescription: {
    fontSize: 12,
    color: theme.colors.gray_text,
    lineHeight: 18,
  },
  menuItemPrice: {
    flexDirection: "row",
    marginTop: "auto",
    height: 30,
    justifyContent: "space-between",
  },
  menuItemPrice1: {
    fontSize: 16,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
    marginTop: "auto",
    marginRight: 5,
  },
  menuItemPrice2: {
    fontSize: 24,
    fontWeight: "bold",
    color: theme.colors.black,
    marginTop: "auto",
  },
  menuItemPrice3: {
    fontSize: 12,
    color: theme.colors.gray_text,
    lineHeight: 18,
    marginTop: "auto",
    marginLeft: 10,
  },
  menuItemPriceCircle: {
    width: 23,
    height: 23,
    borderRadius: 14,
    backgroundColor: theme.colors.gold_deep,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  menuItemPrice4: {
    fontSize: 20,
    lineHeight: 20,
    fontFamily: "Inter-ExtraBold",
    color: theme.colors.white,
  },
  menuItemActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  addButton: {
    flex: 1,
    backgroundColor: "#8B4513",
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  addButtonText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  removeButton: {
    flex: 1,
    backgroundColor: "#dc3545",
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: "center",
  },
  removeButtonText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  footer: {
    backgroundColor: "#8B4513",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderTopWidth: 1,
    borderTopColor: "#e0e0e0",
  },
  selectedText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    textAlign: "center",
  },
});