import { StyleSheet } from "react-native";
import theme from "../../styles/theme";

export const styles = StyleSheet.create({
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.colors.primary_bg,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.gray_text,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.primary_bg,
  },
  closeButton: {
    position: "absolute",
    top: 40,
    right: 20,
    width: 30,
    height: 30,
    borderRadius: 20,
    backgroundColor: theme.colors.gold_deep,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  closeButtonText: {
    fontSize: 24,
    color: theme.colors.white,
    fontWeight: "bold",
    lineHeight: 24,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  productImage: {
    width: "100%",
    height: 310,
    borderRadius: 15,
    marginTop: 20,
    marginBottom: 20,
    resizeMode: "cover",
  },
  nameSection: {
    marginBottom: 15,
    alignItems: "center",
  },
  itemName: {
    fontSize: 24,
    fontFamily: "FuturaPT-Bold",
    color: theme.colors.black,
    textAlign: "center",
  },
  promotionSection: {
    backgroundColor: theme.colors.gold_light,
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: theme.colors.gold_deep,
  },
  promotionText: {
    fontSize: 16,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.gold_deep,
    marginBottom: 5,
  },
  promotionSubText: {
    fontSize: 14,
    fontFamily: "FuturaPT-Light",
    lineHeight: 20,
    color: theme.colors.gray_text,
  },
  descriptionSection: {
    marginBottom: 25,
    padding: 15,
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.gray_text,
  },
  descriptionTitle: {
    fontSize: 16,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
    marginBottom: 10,
  },
  descriptionText: {
    fontSize: 14,
    fontFamily: "FuturaPT-Light",
    color: theme.colors.gray_text,
    lineHeight: 20,
  },
  section: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.gray_text,
  },
  sectionTitle: {
    fontSize: 18,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
    marginBottom: 10,
    lineHeight: 20,
  },
  sectionSubtitle: {
    fontSize: 14,
    fontFamily: "FuturaPT-Light",
    color: theme.colors.gray_text,
    marginBottom: 15,
  },
  noOptionsText: {
    fontSize: 14,
    fontFamily: "FuturaPT-Light",
    color: theme.colors.gray_text,
    textAlign: "center",
    padding: 10,
  },
  sizeOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  sizeButton: {
    flex: 1,
    padding: 15,
    borderWidth: 2,
    borderColor: theme.colors.gray_text,
    borderRadius: 10,
    alignItems: "center",
  },
  selectedSizeButton: {
    borderColor: theme.colors.gold_deep,
    backgroundColor: theme.colors.gold_light,
  },
  sizeText: {
    fontSize: 16,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.black,
  },
  sizePrice: {
    fontSize: 14,
    fontFamily: "FuturaPT-Light",
    color: theme.colors.gray_text,
    marginTop: 5,
  },
  selectedSizeText: {
    color: theme.colors.black,
  },
  iceOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  iceButton: {
    width: "48%",
    padding: 12,
    borderWidth: 2,
    borderColor: theme.colors.gray_text,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  selectedIceButton: {
    borderColor: theme.colors.gold_deep,
    backgroundColor: theme.colors.gold_light,
  },
  iceText: {
    fontSize: 14,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.black,
  },
  selectedIceText: {
    color: theme.colors.black,
  },
  sugarOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 10,
  },
  sugarButton: {
    width: "48%",
    padding: 12,
    borderWidth: 2,
    borderColor: theme.colors.gray_text,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 10,
  },
  selectedSugarButton: {
    borderColor: theme.colors.gold_deep,
    backgroundColor: theme.colors.gold_light,
  },
  sugarText: {
    fontSize: 14,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.black,
  },
  selectedSugarText: {
    color: theme.colors.black,
  },
  quantitySection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
    padding: 15,
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.gray_text,
  },
  quantityLabel: {
    fontSize: 16,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
  },
  quantityControls: {
    flexDirection: "row",
    alignItems: "center",
  },
  quantityButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.gold_deep,
    alignItems: "center",
    justifyContent: "center",
  },
  quantityButtonText: {
    fontSize: 20,
    color: theme.colors.white,
    fontWeight: "bold",
  },
  quantityText: {
    fontSize: 18,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
    marginHorizontal: 15,
    minWidth: 30,
    textAlign: "center",
  },
  totalSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    padding: 15,
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.gray_text,
  },
  totalLabel: {
    fontSize: 18,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
  },
  totalPrice: {
    fontSize: 20,
    fontFamily: "FuturaPT-Bold",
    color: theme.colors.gold_deep,
  },
  orderSummary: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: theme.colors.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.colors.gray_text,
  },
  summaryTitle: {
    fontSize: 16,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.gray_text,
    paddingBottom: 10,
  },
  summaryItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 14,
    fontFamily: "FuturaPT-Medium",
    color: theme.colors.gray_text,
  },
  summaryValue: {
    fontSize: 14,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.black,
  },
  addToCartButton: {
    backgroundColor: theme.colors.gold_deep,
    padding: 18,
    borderRadius: 10,
    alignItems: "center",
  },
  addToCartText: {
    fontSize: 18,
    fontFamily: "FuturaPT-Demi",
    color: theme.colors.white,
  },
});