// screens/VoteRanking/VoteRankingScreen.styles.ts
import { StyleSheet } from "react-native";
import { colors } from "styles";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.primary_bg },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(215, 167, 64, 0.1)",
    backgroundColor: colors.gold_light,
  },
  backButton: {
    width: 35,
    height: 35,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
  },
  headerTitle: { fontSize: 20, fontWeight: "bold", color: colors.black },
  placeholder: { width: 35 },
  tabWrapper: { alignItems: "center", marginVertical: 12 },
  tabContainer: {
    flexDirection: "row",
    backgroundColor: colors.white,
    borderRadius: 25,
    alignItems: "center",
    padding: 5,
    shadowColor: colors.green_deep,
    elevation: 5,
    marginTop: 10,
    marginBottom: 20,
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginHorizontal: 4,
  },
  divider: {
    fontSize: 25,
    color: colors.gray_light,
    fontWeight: "200",
    marginHorizontal: 3,
  },
  tabText: { fontSize: 15, color: colors.gray_text },
  activeTab: { backgroundColor: colors.gold_deep },
  activeTabText: { color: colors.white, fontWeight: "bold" },
  listContainer: { flex: 1, paddingHorizontal: 16 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.white,
    marginBottom: 14,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 20,
    elevation: 3,
    shadowColor: colors.gold_deep,
  },
  rankWrapper: {
    flex: 1,
    alignItems: "flex-start",
  },
  rank: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.green_deep,
  },
  rankGold: { color: "#FFD700" },
  rankSilver: { color: "#C0C0C0" },
  rankBronze: { color: "#CD7F32" },
  avatarWrapper: {
    alignItems: "center",
    marginRight: 10,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 2,
    borderColor: colors.gold_deep,
  },
  user: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.black,
  },
  middleCell: {
    paddingHorizontal: 30,
    alignItems: "center",
  },
  votes: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.green_deep,
  },
  rightCell: {
    flex: 1.5,
    alignItems: "flex-end",
  },
  viewButton: {
    backgroundColor: colors.gold_deep,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  viewButtonText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "600",
  },
});