import { StyleSheet } from "react-native";
import { typography, colors } from "styles"; // ✅ 用统一字体 & 颜色

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.primary_bg },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 5,
    backgroundColor: colors.primary_bg,
    borderBottomWidth: 1,
    borderBottomColor: colors.gold_light,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    textAlign: "center",
    flex: 1,
  },
  postIcon: {
    width: 40,
    height: 40,
    backgroundColor: colors.green_deep,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: { padding: 5 },
  backIcon: { fontSize: 24, color: colors.black },
  floatingPostButton: {
    position: "absolute",
    bottom: 50,
    right: 25,
    zIndex: 25,
  },
  cameraIcon: {
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.green_deep,
    borderRadius: 28,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  cameraIconImage: { width: 28, height: 28, resizeMode: "contain" },

  createPostSection: {
    width: "90%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 15,
    paddingBottom: 25,
    paddingTop: 40,
    flexDirection: "row",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  userAvatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: colors.gold_light,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarEmoji: { fontSize: 24 },
  createPostContainer: { flex: 1 },
  createPostInput: {
    minHeight: 150,
    fontSize: 15,
    color: colors.black,
    textAlignVertical: "top",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colors.gold_deep,
    borderRadius: 10,
    padding: 15,
  },
  closeButtonAbsolute: {
    position: "absolute",
    top: 5,
    right: 10,
    zIndex: 10,
    padding: 5,
  },
  closeButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.gray_deep,
  },
  createPostActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.gray_button,
    borderRadius: 20,
  },
  actionIcon: { fontSize: 18, marginRight: 4 },
  actionText: {
    fontSize: 14,
    color: colors.gray_deep,
    fontWeight: "500",
  },
  postButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: "#e2e8f0",
    borderRadius: 20,
  },
  postButtonActive: {
    backgroundColor: colors.gold_deep,
  },
  postButtonText: {
    fontSize: 14,
    color: colors.gray_text,
    fontWeight: "600",
  },
  postButtonTextActive: { color: colors.white },

  feedContainer: { flex: 1 },
  postCard: { backgroundColor: colors.white, marginBottom: 8 },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  postUserInfo: { flexDirection: "row", alignItems: "center" },
  postAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray_light,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  username: { fontSize: 14, fontWeight: "600", color: colors.black },
  timeAgo: { fontSize: 12, color: colors.gray_text, marginTop: 2 },
  moreButton: { padding: 5 },
  moreIcon: { fontSize: 18, color: colors.gray_deep },
  postImage: {
    width: "100%", // 占满父容器
    aspectRatio: 1, // 高度 = 宽度
    resizeMode: "cover", // 图片超出部分裁切，保证正方形不拉伸
  },

  postContent: { paddingHorizontal: 16, paddingVertical: 12 },
  caption: { fontSize: 14, color: colors.black, lineHeight: 20 },

  postActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  leftActions: { flexDirection: "row", alignItems: "center" },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 20,
    paddingVertical: 5,
  },
  actionButtonIcons: {
    width: 24,
    height: 24,

  },
  actionCount: {
    fontSize: 14,
    color: "#4a5568",
    fontWeight: "500",
    marginLeft: 4,
  },

  commentBox: {
    flexDirection: "row",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: colors.gray_light,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  commentInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 6,
    paddingHorizontal: 8,
    color: colors.black,
  },
  commentPostButton: {
    marginLeft: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: colors.gray_light,
  },
  commentPostButtonActive: {
    backgroundColor: colors.gold_deep,
  },
  commentPostButtonText: {
    fontSize: 14,
    color: colors.gray_text,
    fontWeight: "600",
  },
  commentPostButtonTextActive: { color: colors.white },

  bottomSpacing: { height: 20 },

  commentSection: {
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  commentRow: {
    flexDirection: "row",
    marginBottom: 10,
  },
  commentUser: {
    fontWeight: "600",
    color: colors.gray_deep,
    marginRight: 4,
  },
  commentText: {
    color: colors.gray_deep,
    flexShrink: 1,
  },
  noCommentText: {
    color: colors.gray_text,
    fontStyle: "italic",
    marginBottom: 8,
  },
  previewContainer: {
    marginTop: 10,
    marginBottom: 20,
    position: "relative",
    alignItems: "flex-start",
  },
  previewImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  removeImageButton: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  removeImageText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
});

// 给 Button 用的
export const newStyles = StyleSheet.create({
  deleteModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  editModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 16,
    textAlign: "center",
  },
  buttonsAll: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  buttons: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginHorizontal: 5,
  },
  buttonMessage: {
    fontSize: 16,
    color: colors.gray_deep,
    marginBottom: 40,
    textAlign: "center",
  },
  buttonLeft: {
    paddingVertical: 12,
    paddingHorizontal: 50,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.gray_light,
  },
  buttonRight: {
    paddingVertical: 12,
    paddingHorizontal: 50,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.gold_deep,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.black,
  },
  editInput: {
    minHeight: 150,
    borderWidth: 1,
    borderColor: colors.gray_light,
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    marginBottom: 20,
    textAlignVertical: "top",
  },
  // closeIcon: {
  //   fontSize: 24,
  //   color: colors.black,
  //   fontWeight: "bold",
  // },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  dropdownOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 60,
  },
});

// 给 Post Dropdown 用的
export const newStylesdropdown = StyleSheet.create({
  dropdownMenu: {
    position: "absolute",
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    minWidth: 120,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: 15,
    color: colors.black,
  },
  dropdownItemDelete: {
    color: "#e53e3e",
  },
});

// 给 Share 用的
export const shareStyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end",
    alignItems: "center",
    zIndex: 10,
  },
  shareSuccessModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
  },
  shareSuccessText: {
    fontSize: 16,
    color: colors.black,
    textAlign: "center",
  },
  shareContainer: {
    width: "100%",
    backgroundColor: colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 15,
    paddingBottom: 30,
  },
  shareHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  shareTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
  },
  closeButton: {
    padding: 5,
  },
  closeIcon: {
    fontSize: 24,
    color: colors.black,
    fontWeight: "bold",
  },
  shareOptionsHorizontal: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  shareOptionHorizontal: {
    alignItems: "center",
    marginHorizontal: 0,
    marginBottom: 15,
    width: 60,
  },
  shareOptionIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.gray_light,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  shareOptionIconText: {
    fontSize: 20,
  },
  shareOptionText: {
    fontSize: 12,
    color: colors.black,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 16,
    color: "#2d3748",
    fontWeight: "600",
  },
});
