import { StyleSheet } from "react-native";
import { colors } from "styles";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.primary_bg },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderBottomWidth: 1,
    borderBottomColor: colors.gold_light,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    textAlign: "center",
    flex: 1,
  },
  postIcon: {
    width: 40,
    height: 40,
    backgroundColor: colors.gold_deep,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.white,
  },
  backButton: {
    width: 35,
    height: 35,
    borderRadius: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  createPostSection: {
    width: "90%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 15,
    paddingBottom: 25,
    paddingTop: 40,
    flexDirection: "row",
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  userAvatar: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: colors.gold_light,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  avatarEmoji: { fontSize: 24 },
  createPostContainer: { flex: 1 },
  createPostInput: {
    minHeight: 150,
    fontSize: 15,
    color: colors.black,
    textAlignVertical: "top",
    marginBottom: 15,
    borderWidth: 1,
    borderColor: colors.gold_deep,
    borderRadius: 10,
    padding: 15,
  },
  closeButtonAbsolute: {
    position: "absolute",
    top: 5,
    right: 10,
    zIndex: 10,
    padding: 5,
  },
  closeButtonText: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.gray_deep,
  },
  createPostActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  photoButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.gray_button,
    borderRadius: 20,
  },
  actionIcon: { fontSize: 18, marginRight: 4 },
  actionText: {
    fontSize: 14,
    color: colors.gray_deep,
    fontWeight: "500",
  },
  postButton: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    backgroundColor: "#e2e8f0",
    borderRadius: 20,
  },
  postButtonActive: {
    backgroundColor: colors.gold_deep,
  },
  postButtonText: {
    fontSize: 14,
    color: colors.gray_text,
    fontWeight: "600",
  },
  postButtonTextActive: { color: colors.white },

  feedContainer: { flex: 1 },
  postCard: { backgroundColor: colors.white, marginBottom: 8 },
  postHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  postUserInfo: { flexDirection: "row", alignItems: "center" },
  postAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.gray_light,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  username: { fontSize: 14, fontWeight: "600", color: colors.black },
  timeAgo: { fontSize: 12, color: colors.gray_text, marginTop: 2 },
  moreButton: { padding: 5 },
  moreIcon: { fontSize: 18, color: colors.gray_deep },
  postImage: {
    width: "100%", // 占满父容器
    aspectRatio: 1, // 高度 = 宽度
    resizeMode: "cover", // 图片超出部分裁切，保证正方形不拉伸
  },

  postContent: { paddingHorizontal: 16, paddingVertical: 15, marginBottom: 5 },
  caption: { fontSize: 14, color: colors.black, lineHeight: 20 },

  postActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  leftActions: { flexDirection: "row", alignItems: "center", flex: 1 },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 20,
    paddingVertical: 5,
  },
  actionButtonIcons: {
    width: 24,
    height: 24,
  },
  saveButton: {
    position: "absolute",
    top: 2,
    right: 20,
    padding: 5,
  },
  actionCount: {
    fontSize: 14,
    color: "#4a5568",
    fontWeight: "500",
    marginLeft: 4,
  },
  bottomSpacing: { height: 20 },
  previewContainer: {
    marginTop: 10,
    marginBottom: 20,
    position: "relative",
    alignItems: "flex-start",
  },
  previewImage: {
    width: 120,
    height: 120,
    borderRadius: 8,
  },
  removeImageButton: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "rgba(0,0,0,0.6)",
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  removeImageText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },

  // comment
  commentInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
    backgroundColor: colors.white,
  },
  commentTextInput: {
    flex: 1,
    fontSize: 14,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#f8f9fa",
    borderRadius: 20,
    marginRight: 8,
    color: colors.black,
    maxHeight: 80,
  },
  commentSection: {
    paddingHorizontal: 12,
    paddingTop: 20,
    paddingBottom: 0,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  commentRow: {
    flexDirection: "row",
    marginBottom: 20,
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  commentAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.gold_light,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  commentAvatarText: {
    fontSize: 14,
    fontWeight: "600",
  },
  commentContent: {
    flex: 1,
    backgroundColor: colors.primary_bg,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  commentUserInfo: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 2,
  },
  commentUser: {
    fontWeight: "600",
    color: colors.gray_deep,
    fontSize: 13,
    marginRight: 6,
  },
  commentTime: {
    fontSize: 11,
    color: colors.gray_text,
    marginLeft: 8,
  },
  commentText: {
    color: colors.black,
    fontSize: 14,
    lineHeight: 18,
    marginBottom: 4,
  },
  commentActions: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  commentLikeButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 2,
    paddingHorizontal: 6,
    marginRight: 10,
  },
  commentLikeIcon: {
    fontSize: 15,
    marginRight: 4,
    color: colors.gray_deep,
  },
  commentLikeCount: {
    fontSize: 11,
    color: colors.gray_text,
  },
  noCommentText: {
    color: colors.gray_text,
    fontStyle: "italic",
    marginBottom: 8,
    textAlign: "center",
    paddingVertical: 20,
  },

  // reply
  replyIndicator: {
    flexDirection: "row",
    // justifyContent: 'space-between',
    alignItems: "center",
    backgroundColor: "#f7fafc",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  replyIndicatorText: {
    fontSize: 12,
    color: "#4a5568",
    fontWeight: "500",
  },
  cancelReplyText: {
    fontSize: 12,
    color: "#e53e3e",
    fontWeight: "light",
  },
  repliesContainer: {
    marginLeft: 10,
    marginTop: 0,
    paddingLeft: 12,
    borderLeftWidth: 2,
    borderLeftColor: colors.gold_deep,
    marginBottom: 15,
  },
  replyRow: {
    flexDirection: "row",
    marginBottom: 6,
    flexWrap: "wrap",
    marginLeft: 0,
  },
  replyUser: {
    fontWeight: "600",
    color: colors.gold_deep,
    marginRight: 4,
    fontSize: 13,
  },
  replyText: {
    color: colors.black,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
  },
  replyTo: {
    color: colors.gold_deep,
    fontWeight: "600",
  },
  sendButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    backgroundColor: colors.gold_deep,
  },
  sendButtonText: {
    fontSize: 14,
    color: colors.white,
    fontWeight: "600",
  },

  // 设计师标识
  designerBadge: {
    backgroundColor: colors.green_deep,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 104,
    marginLeft: 3,
  },
  designerBadgeText: {
    fontSize: 10,
    color: colors.white,
    fontWeight: "bold",
  },

  // 评论点赞高亮
  likedComment: {
    color: "#ff2442", // 小红书红
  },
  likedCommentText: {
    color: "#ff2442",
    fontWeight: "600",
  },
});

// 给 Button 用的
export const buttonStyles = StyleSheet.create({
  deleteModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  editModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 16,
    textAlign: "center",
  },
  buttonsAll: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  buttonMessage: {
    fontSize: 16,
    color: colors.gray_deep,
    marginBottom: 40,
    textAlign: "center",
  },
  buttonLeft: {
    paddingVertical: 12,
    paddingHorizontal: 50,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.gray_light,
  },
  buttonRight: {
    paddingVertical: 12,
    paddingHorizontal: 50,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.gold_deep,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.black,
  },
  editInput: {
    minHeight: 150,
    borderWidth: 1,
    borderColor: colors.gray_light,
    borderRadius: 8,
    padding: 12,
    fontSize: 15,
    marginBottom: 20,
    textAlignVertical: "top",
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  dropdownOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 60,
  },
});

// 给 Post Dropdown 用的
export const newStylesdropdown = StyleSheet.create({
  dropdownMenu: {
    position: "absolute",
    backgroundColor: colors.white,
    borderRadius: 8,
    padding: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    minWidth: 120,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: 15,
    color: colors.black,
  },
  dropdownItemDelete: {
    color: "#e53e3e",
  },
});

// 给 Share 用的
export const shareStyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "flex-end",
    alignItems: "center",
    zIndex: 10,
  },
  shareSuccessModal: {
    width: "80%",
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 20,
    alignItems: "center",
  },
  sharePreviewTitle: {
    fontSize: 15,
    color: colors.black,
    fontWeight: "semibold",
    marginBottom: 10,
  },
  sharePreviewText: {
    fontSize: 15,
    color: colors.black,
    fontWeight: "semibold",
    marginBottom: 10,
  },
  shareSuccessText: {
    fontSize: 16,
    color: colors.black,
    textAlign: "center",
  },
  shareContainer: {
    width: "100%",
    backgroundColor: colors.white,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 15,
    paddingBottom: 30,
  },
  shareHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  shareTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
  },
  closeButton: {
    padding: 5,
  },
  closeIcon: {
    fontSize: 24,
    color: colors.black,
    fontWeight: "bold",
  },
  shareOptionsHorizontal: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  shareOptionHorizontal: {
    alignItems: "center",
    marginHorizontal: 0,
    marginBottom: 15,
    width: 60,
  },
  shareOptionIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.gray_light,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  shareOptionIconText: {
    fontSize: 20,
  },
  shareOptionText: {
    fontSize: 12,
    color: colors.black,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "#e2e8f0",
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: "center",
  },
  cancelButtonText: {
    fontSize: 16,
    color: "#2d3748",
    fontWeight: "600",
  },
});
