// 给话题讨论用的
import { StyleSheet } from "react-native";
import { colors } from "styles";


export const topicStyles = StyleSheet.create({
  tabContainer: {
    flexDirection: "row",
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray_light,
  },
  tab: {
    flex: 1,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  activeTab: {
    borderBottomWidth: 3,
    borderBottomColor: colors.gold_deep,
    borderTopLeftRadius:50,
    borderTopRightRadius:50,
  },
  tabText: {
    fontSize: 15,
    color: colors.gray_text,
    fontWeight: "500",
  },
  activeTabText: {
    color: colors.gold_deep,
    fontWeight: "600",
  },
  topicsContainer: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 16,
    marginTop: 8,
  },
  topicCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.gray_light,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  hotTopicCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: colors.gold_light,
    shadowColor: colors.gold_deep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
    position: "relative",
  },
  participationIndicator: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: colors.gold_deep,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  topicHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  topicTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.black,
    flex: 1,
    marginRight: 8,
  },
  hotBadge: {
    backgroundColor: "#ff6b6b",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  hotBadgeText: {
    fontSize: 10,
    color: colors.white,
    fontWeight: "bold",
  },
  topicDescription: {
    fontSize: 14,
    color: colors.gray_text,
    marginBottom: 12,
    lineHeight: 20,
  },
  activityIndicator: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  activityDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  activityHigh: {
    backgroundColor: "#10b981",
  },
  activityMedium: {
    backgroundColor: "#f59e0b",
  },
  activityLow: {
    backgroundColor: "#6b7280",
  },
  activityText: {
    fontSize: 12,
    color: colors.gray_text,
    marginLeft: 4,
  },
  topicStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  statContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  statIcon: {
    fontSize: 14,
    marginRight: 4,
  },
  statText: {
    fontSize: 12,
    color: colors.gray_text,
    fontWeight: "500",
  },
  trendingIndicator: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  trendingText: {
    fontSize: 11,
    color: "#059669",
    fontWeight: "600",
  },
  interactionPreview: {
    flexDirection: "row",
    alignItems: "center",
  },
  previewAvatar: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.gold_light,
    marginRight: -4,
    borderWidth: 1,
    borderColor: colors.white,
  },
  moreParticipants: {
    fontSize: 11,
    color: colors.gray_text,
    marginLeft: 8,
  },
  selectedTopicHeader: {
    padding: 16,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray_light,
  },
  backToTopics: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  backText: {
    fontSize: 14,
    color: "#666",
    marginLeft: 6,
  },
  selectedTopicTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.black,
    marginBottom: 6,
  },
  selectedTopicDesc: {
    fontSize: 14,
    color: colors.gray_text,
    lineHeight: 20,
  },
  emptyTopic: {
    padding: 40,
    alignItems: "center",
    backgroundColor: colors.white,
    margin: 16,
    borderRadius: 12,
  },
  emptyIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.gray_light,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  emptyIcon: {
    fontSize: 24,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.black,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: colors.gray_text,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 20,
  },
  createTopicButton: {
    backgroundColor: colors.gold_deep,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 20,
  },
  createTopicButtonText: {
    fontSize: 14,
    color: colors.white,
    fontWeight: "600",
  },
});